version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: "your-secret-key"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: >
      sh -c "npm start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend

# volumes:
#   - db_data:/app/dev.db
volumes:
  db_data:
  # Removed db_data since SQLite is file-based