version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: "your-secret-key"
    ports:
      - "3000:3000"
    volumes:
      - ./user-service:/app
    # command: >
    #   sh -c "npm start"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: "your-secret-key"
    ports:
      - "3001:3001"
    volumes:
      - ./auth-service:/app
    # command: >
    #   sh -c "npm start"

  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: "your-secret-key"
    ports:
      - "4000:4000"
    volumes:
      - ./chat-service:/app
    # command: >
    #   sh -c "npm start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    depends_on:
      - user-service
      - auth-service
      - chat-service