version: '3.8'


services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: "your-secret-key"
      DATABASE_URL: "file:./data.db"
    ports:
      - "3002:3002"
    networks:
      - app-network
    volumes:
      - ./database/prisma:/app/prisma

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: "your-secret-key"
      DATABASE_URL: "file:./data.db"
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./database/prisma:/app/prisma
    depends_on:
      - database
    # command: >
    #   sh -c "npm start"

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: "your-secret-key"
      DATABASE_URL: "file:./data.db"
    ports:
      - "3001:3001"
    networks:
      - app-network
    volumes:
      - ./database/prisma:/app/prisma
    depends_on:
      - database
    # command: >
    #   sh -c "npm start"

  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: "your-secret-key"
      DATABASE_URL: "file:./data.db"
    ports:
      - "4000:4000"
    networks:
      - app-network
    volumes:
      - ./database/prisma:/app/prisma
    depends_on:
      - database
  #   command: >
  #     sh -c "npm start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    networks:
      - app-network
    depends_on:
      - user-service
      - auth-service
      - chat-service

  nginx:
    image: nginx:latest
    ports:
      - "3004:3004"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - user-service
      - auth-service
      - chat-service
    networks:
      - app-network

volumes:
  database:

networks:
  app-network:
    driver: bridge