version: '3.8'


services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: "your-secret-key"
      DATABASE_URL: "file:./data.db"
    ports:
      - "3002:3002"
    networks:
      - app-network
    volumes:
      - ./database/prisma:/app/prisma

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: "your-secret-key"
      DATABASE_URL: "file:./data.db"
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./database/prisma:/app/prisma
    depends_on:
      - database
    # command: >
    #   sh -c "npm start"

  tournament-service:
    build:
      context: ./tournament-service
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: "your-secret-key"
      DATABASE_URL: "file:./data.db"
    ports:
      - "3004:3004"
    networks:
      - app-network
    volumes:
      - ./database/prisma:/app/prisma
    depends_on:
      - database
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: "your-secret-key"
      DATABASE_URL: "file:./data.db"
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: "http://localhost:3001/api/auth/google/callback"
    ports:
      - "3001:3001"
    networks:
      - app-network
    volumes:
      - ./database/prisma:/app/prisma
    depends_on:
      - database
    # command: >
    #   sh -c "npm start"

  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    environment:
      JWT_SECRET: "your-secret-key"
      DATABASE_URL: "file:./data.db"
    ports:
      - "4000:4000"
    networks:
      - app-network
    volumes:
      - ./database/prisma:/app/prisma
    depends_on:
      - database
  #   command: >
  #     sh -c "npm start"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    networks:
      - app-network
    depends_on:
      - user-service
      - auth-service
      - chat-service
      - tournament-service

volumes:
  database:

networks:
  app-network:
    driver: bridge